server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        web: INFO

spring:
  application:
    name: waes-interview-web
  main:
    allow-bean-definition-overriding: true
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  h2:
    console:
      enabled: true
  mvc:
    locale: en
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    time-zone: UTC
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      INDENT_OUTPUT: true
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    parser:
      ALLOW_UNQUOTED_FIELD_NAMES: true
    generator:
      WRITE_BIGDECIMAL_AS_PLAIN: true